### PR TITLE
Add GUI for Neuropixels V1e

### LINKED ISSUE #106: Headstage Neuropixel 1.0e - GUI
Closely related to #100, and is focused on adding GUI elements on top of the work done in the issue-100 branch.

### PR DESCRIPTION
**Pull request by bparks13**
This PR aims to add a dialog GUI for the `NeuropixelsV1e` headstage. 

Controls are based on `NeuropixelsV2e` GUI, for more info on the controls see #214.

One major difference between V1 and V2 is that V1 has two separate calibration files that are required (Gain and ADC). The probe will not be visible unless both files exist and are selected.

Closes #106

### CODE REVIEW

**Comment by jonnew** [comment]
We will need to bring the changes from #243 into this PR, I suppose.

**Comment by bparks13** [comment]
@jonnew actually we won't need to, the scaling issues occurred at the device/headstage level, not the common framework level. Meaning, I was able to fix the `NeuropixelsV2e` dialogs in #243, which modifies the dialogs that are in main, and I took the same steps to fix the `NeuropixelsV1e` dialogs. I just need to finish testing and push that commit to this PR.

**Comment by jonnew** [comment]
@bparks13 I made some minor changes to make the NP GUIs more uniform. Once you confirm I have not broken anything, lets merge this.

**Review by jonnew — APPROVED** [review]
Please perform a final sanity check on my latest small changes and then we can merge.

**Pull request merged**
